// ignore_for_file: constant_identifier_names

enum PacketType {
  START_ROUND,
  SHOW_LEADERBOARD,
  SUBMIT_ANSWER,
  JOKER_REQUEST,
  JOKER_RESPONSE,
  CORRECT_ANSWER,
  REGISTER,
  UPDATE_PLAYER_LIST,
  PLAYER_ANSWERED,
}
